Removed suse specific code; Added command to call nagios_downtime; Added return code handling
git-svn-id: https://www.nagiosforge.org/svn/nagios_downtime@10 2d24d2ea-3857-44fe-be62-836b37ce8733

diff --git a/perl/trunk/nagios_downtime.init b/perl/trunk/nagios_downtime.init
--- a/perl/trunk/nagios_downtime.init
+++ b/perl/trunk/nagios_downtime.init
@@ -16,8 +16,8 @@
 # to the Nagios cmd.cgi to be able to post a downtime.
 ### END INIT INFO
 
-#BAR_BIN=/usr/bin/nagios_downtime
-BAR_BIN=./nagios_downtime
+BAR_BIN=/usr/bin/nagios_downtime
+#BAR_BIN=./nagios_downtime
 
 # Check for missing binaries
 test -x $BAR_BIN || {
@@ -29,19 +29,18 @@ test -x $BAR_BIN || {
 	fi;
 }
 
-# Load the rc.status script for this service.
-. /etc/rc.status
-
-# Reset status of this service
-rc_reset
-
 case "$1" in
     stop)
         echo -n "Running nagios_downtime script... "
-
-        # Remember status and be verbose
-        rc_status -v
-				exit 0
+				$BAR_BIN
+				
+				if [ $? -eq 0 ]; then
+					echo "done."
+					exit 0
+				else
+					echo "ERROR"
+					exit 1
+				fi
         ;;
     *)
         # If no parameters are given, print which are avaiable
